### PR TITLE
Update List-of-TODOs

### PR DESCRIPTION
**Pull request by dev-b8u8-github1**
Added one more task to do. Please merge to main.

### CODE REVIEW

**Comment by dev-b8u8-github1** [comment]
Please merge this great task to do!

**Comment by dev-b8u8-github1** [comment]
Thanks Livingstonic. Please review

**Comment by livingstonic** [comment]
Yes I have reviewed and I like it.

**Review by livingstonic — CHANGES_REQUESTED** [review]
Add a task to add more collaborators please

**Review by livingstonic — APPROVED** [review]
Yeah, that seem fab! Thank you.

**Comment by dev-b8u8-github1** [comment]
I've added a link to the Readme please review

**Review by livingstonic — APPROVED** [review]
That's fine. Thanks.

**Pull request merged**
